# Generated by Django 3.2.5 on 2021-07-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20210713_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='established_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='no_of_employees',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='no_of_offices',
        ),
    ]
