# Generated by Django 3.2.5 on 2021-07-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20210721_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.CharField(blank='True', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.CharField(blank='True', default='', max_length=255),
        ),
    ]
