# Generated by Django 3.2.5 on 2021-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20210722_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.CharField(blank='True', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.CharField(blank='True', default='', max_length=255),
        ),
    ]
