# Generated by Django 3.2.5 on 2021-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20210713_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_amount_spend',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
