# Generated by Django 3.2.5 on 2021-07-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_customer_total_amount_spend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_amount_spend',
        ),
    ]
