# Generated by Django 3.2.5 on 2021-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_customer_total_amount_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_spending',
            field=models.IntegerField(default=0),
        ),
    ]
