# Generated by Django 3.2.5 on 2021-07-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='symbol',
            field=models.CharField(default='', max_length=255),
        ),
    ]
