# Generated by Django 3.2.5 on 2021-07-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_rename_symbol_invoice_currency_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_spending',
        ),
    ]
